
export default new Map([
["src/content/posts/2026-05-30-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-05-30-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-05-31-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-05-31-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-01-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-01-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2025-05-life-walk.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2025-05-life-walk.mdx&astroContentModuleFlag=true")],
["src/content/posts/2025-05-tech-cursor-blog.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2025-05-tech-cursor-blog.mdx&astroContentModuleFlag=true")],
["src/content/posts/2025-05-economy-inflation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2025-05-economy-inflation.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-02-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-02-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-03-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-03-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-05-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-05-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-04-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-04-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-06-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-06-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-10-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-10-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-11-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-11-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-12-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-12-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-13-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-13-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-14-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-14-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-07-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-07-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-09-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-09-tech-daily.mdx&astroContentModuleFlag=true")],
["src/content/posts/2026-06-08-tech-daily.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F2026-06-08-tech-daily.mdx&astroContentModuleFlag=true")]]);
		